title: Smitkumar Patel Portfolio
logo: /assets/img/1696650798667.jpeg
description: Aspiring Software Engineer.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
url: "https://smit2444.github.io/"
